/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproyectpoo.View;

import com.mycompany.finalproyectpoo.DAO.Conexion;
import com.mycompany.finalproyectpoo.Models.ExamenFisico;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author juana
 */
public class examen_fisico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(examen_fisico.class.getName());

    /**
     * Creates new form examen_fisico
     */
    private int id_historia;
    public examen_fisico(int id_historia) {
        this.id_historia = id_historia;
        initComponents();
    }

    private examen_fisico() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCondicion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboDeshi = new javax.swing.JComboBox<>();
        txtTemperatura = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboMucosa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtFRespiratoria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtFCardiaca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRCapilar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtPulso = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservacion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCondicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 110, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Condicoin Corporal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, -1));

        comboDeshi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));
        comboDeshi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDeshiActionPerformed(evt);
            }
        });
        getContentPane().add(comboDeshi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 90, -1));
        getContentPane().add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 110, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Temperatura:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 130, -1));

        ComboMucosa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rosa", "Pálida", "Cianótica", "Ictérica", "Congestionada/Roja", "Seca/Húmeda" }));
        ComboMucosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboMucosaActionPerformed(evt);
            }
        });
        getContentPane().add(ComboMucosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 90, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Deshidratacion");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 120, -1));
        getContentPane().add(txtFRespiratoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 110, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Frecuencia Cardiaca:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 160, -1));
        getContentPane().add(txtFCardiaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 110, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Frecuencia Respiratoria:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, -1));

        txtRCapilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRCapilarActionPerformed(evt);
            }
        });
        getContentPane().add(txtRCapilar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Relleno Capilar:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 140, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Pulso:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, -1));

        txtPulso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulsoActionPerformed(evt);
            }
        });
        getContentPane().add(txtPulso, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Mucosas:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 90, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Observaciones:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 130, -1));

        txtObservacion.setColumns(20);
        txtObservacion.setRows(5);
        jScrollPane1.setViewportView(txtObservacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, -1, 90));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Examen Fisico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 160, 30));

        jButton1.setText("Guardar y Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 170, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finalproyectpoo/Imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboMucosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboMucosaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboMucosaActionPerformed

    private void comboDeshiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDeshiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboDeshiActionPerformed

    private void txtPulsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulsoActionPerformed

    private void txtRCapilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRCapilarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRCapilarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        String Condicion = txtCondicion.getText();
        String Temperatura = txtTemperatura.getText();
        String Respirar = txtFRespiratoria.getText();
        String Cardiaca = txtFCardiaca.getText();
        String Capilar = txtRCapilar.getText();
        String Pulso = txtPulso.getText();
        String Mucosa = ComboMucosa.getSelectedItem().toString();//opcion seleccionada del combo box;
        String Hidratacion = comboDeshi.getSelectedItem().toString();
        String Observacion = txtObservacion.getText();
        
        //Ahora vamos a crear el objeto para hacer la consulta
        
        ExamenFisico ef = new ExamenFisico(Condicion,Temperatura,Respirar,Cardiaca,
                Capilar,Pulso,Mucosa,Hidratacion,Observacion,this.id_historia);
       
        try (Connection con = Conexion.conectar()) {
            String sql = "INSERT INTO examen_fisico (condicion_corporal, temperatura,"
                    + " frecuencia_respiratoria, frecuencia_cardiaca, relleno_capilar,"
                    + " pulso, mucosas, deshidratacion,"
                    + " observaciones, id_historia) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            // En este caso se hace el statement para poder imprimir por pantalla el id de la mascota
            PreparedStatement ps = con.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);

            ps.setString(1,ef.getCondicion_corporal());
            ps.setString(2,ef.getTemperatura());
            ps.setString(3, ef.getFrecuencia_respiratoria());
            ps.setString(4,ef.getFrecuencia_cardiaca());
            ps.setString(5,ef.getRelleno_capilar());
            ps.setString(6,ef.getPulso());
            ps.setString(7, ef.getMucosas());
            ps.setString(8,ef.getDeshidratacion());
            ps.setString(9,ef.getObservaciones());
            ps.setInt(10,this.id_historia);
        
            //Hacemos esto para que se cree la siguiente ventana y que salga el mensaje de que se guardo en la base de datos 
            int rowsInserted = ps.executeUpdate(); // guarda datos
            if (rowsInserted > 0) { // sólo se abre si se guardó bien
                interfasHallazgosClinicos hallazgosframe = new interfasHallazgosClinicos(this.id_historia);
                hallazgosframe.setLocationRelativeTo(null); // centra el nuevo frame
                hallazgosframe.setVisible(true); // muestra la ventana
                this.dispose(); // cierra el frame actual si ya no lo necesitas
            }
            
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new examen_fisico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMucosa;
    private javax.swing.JComboBox<String> comboDeshi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCondicion;
    private javax.swing.JTextField txtFCardiaca;
    private javax.swing.JTextField txtFRespiratoria;
    private javax.swing.JTextArea txtObservacion;
    private javax.swing.JTextField txtPulso;
    private javax.swing.JTextField txtRCapilar;
    private javax.swing.JTextField txtTemperatura;
    // End of variables declaration//GEN-END:variables
}
