/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproyectpoo.View;

import com.mycompany.finalproyectpoo.DAO.Conexion;
import com.mycompany.finalproyectpoo.Models.ExamenFisico;
import com.mycompany.finalproyectpoo.Models.HallazgosClinicos;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class interfasHallazgosClinicos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfasHallazgosClinicos.class.getName());

    /**
     * Creates new form interfasHallazgosClinicos
     */
    
    private int id_historia;
    public interfasHallazgosClinicos(int id_historia) {
        this.id_historia = id_historia;
        initComponents();
    }

    private interfasHallazgosClinicos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ComboPielPelaje = new javax.swing.JComboBox<>();
        ComboGlangleosLinfatico = new javax.swing.JComboBox<>();
        ComboDigestivo = new javax.swing.JComboBox<>();
        ComboRespiratorio = new javax.swing.JComboBox<>();
        ComboEndocrino = new javax.swing.JComboBox<>();
        ComboNervioso = new javax.swing.JComboBox<>();
        ComboUrinario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ComboReproductivo = new javax.swing.JComboBox<>();
        ComboMusculoEsqueletico = new javax.swing.JComboBox<>();
        ComboPalpacionRectal = new javax.swing.JComboBox<>();
        ComboHallazgosRelevantes = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Glangleos Linfatico:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Piel y Pelaje:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Digestivo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Respiratorio:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Endocrino:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Nervioso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Urinario:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Hallazgos Clinicos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 300, 40));

        ComboPielPelaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Alopecia (pérdida de pelo)", "Presencia de pulgas o garrapatas" }));
        ComboPielPelaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPielPelajeActionPerformed(evt);
            }
        });
        getContentPane().add(ComboPielPelaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, -1));

        ComboGlangleosLinfatico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normales", "Aumentados de tamaño", "Dolorosos a la palpación" }));
        getContentPane().add(ComboGlangleosLinfatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, -1));

        ComboDigestivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Vómitos", "Diarrea" }));
        ComboDigestivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboDigestivoActionPerformed(evt);
            }
        });
        getContentPane().add(ComboDigestivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 130, -1));

        ComboRespiratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Tos", "Dificultad respiratoria (disnea)" }));
        ComboRespiratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboRespiratorioActionPerformed(evt);
            }
        });
        getContentPane().add(ComboRespiratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 130, -1));

        ComboEndocrino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Polidipsia / Poliuria (mucha sed o micción)", "Pérdida de peso sin causa aparente" }));
        getContentPane().add(ComboEndocrino, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 130, -1));

        ComboNervioso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Convulsiones", "Descoordinación (ataxia)" }));
        getContentPane().add(ComboNervioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 130, -1));

        ComboUrinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Dificultad para orinar (disuria)", "Orina con sangre (hematuria)" }));
        getContentPane().add(ComboUrinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 130, -1));

        jButton1.setText("Guardar y Continuar");
        jButton1.setMaximumSize(new java.awt.Dimension(72, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(72, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 190, 34));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Reproductivo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Músculo Esqueletico:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Palpación Rectal:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Hallazgo Relevantes:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        ComboReproductivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Secreción vaginal o prepucial", "Inflamación genital o testicular" }));
        getContentPane().add(ComboReproductivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 130, -1));

        ComboMusculoEsqueletico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Cojera", "Dolor articular" }));
        getContentPane().add(ComboMusculoEsqueletico, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 130, -1));

        ComboPalpacionRectal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Dolor a la palpación", "Masas o engrosamientos detectables" }));
        getContentPane().add(ComboPalpacionRectal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 130, -1));

        ComboHallazgosRelevantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin hallazgos relevantes", "Lesiones múltiples", "Signos de dolor o malestar general" }));
        getContentPane().add(ComboHallazgosRelevantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 130, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finalproyectpoo/Imagenes/Marca_Final.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 830, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboPielPelajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPielPelajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboPielPelajeActionPerformed

    private void ComboDigestivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboDigestivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboDigestivoActionPerformed

    private void ComboRespiratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboRespiratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboRespiratorioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String PielPelaje = ComboPielPelaje.getSelectedItem().toString();
        String GlangleosLinfatico = ComboGlangleosLinfatico.getSelectedItem().toString();
        String Digestivo = ComboDigestivo.getSelectedItem().toString();
        String Respiratorio = ComboRespiratorio.getSelectedItem().toString();
        String Endocrino = ComboEndocrino.getSelectedItem().toString();
        String Nervioso = ComboNervioso.getSelectedItem().toString();
        String urinario = ComboUrinario.getSelectedItem().toString();//opcion seleccionada del combo box;
        String Reproductivo = ComboReproductivo.getSelectedItem().toString();
        String MusculoEsque = ComboMusculoEsqueletico.getSelectedItem().toString();
        String PalpacionRec = ComboPalpacionRectal.getSelectedItem().toString();
        String HallazgosRele = ComboHallazgosRelevantes.getSelectedItem().toString();
        //Ahora vamos a crear el objeto para hacer la consulta
        
        HallazgosClinicos hc = new HallazgosClinicos(PielPelaje,GlangleosLinfatico,Digestivo,Respiratorio,
                Endocrino,Nervioso ,urinario,Reproductivo,MusculoEsque,PalpacionRec,HallazgosRele, this.id_historia);
       
        try (Connection con = Conexion.conectar()) {
            String sql = "INSERT INTO hallazgos_clinicos (piel_pelage, gangleos_linfatico,"
                    + " digestivo, respiratorio, endocrino, nervioso, urinario, reproductivo,"
                    + " musculo_esqueletico, palpacion_rectal,hallazgos_relevantes, id_historia) VALUES (?,?,?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            // En este caso se hace el statement para poder imprimir por pantalla el id de la mascota
            PreparedStatement ps = con.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);

            ps.setString(1,hc.getPiel_pelage());
            ps.setString(2,hc.getGangleos_linfatico());
            ps.setString(3,hc.getDigestivo());
            ps.setString(4,hc.getRespiratorio());
            ps.setString(5,hc.getEndocrino());
            ps.setString(6,hc.getNervioso());
            ps.setString(7,hc.getUrinario());
            ps.setString(8,hc.getReproductivo());
            ps.setString(9,hc.getMusculo_esqueletico());
            ps.setString(10,hc.getPalpacion_rectal());
            ps.setString(11,hc.getHallazgos_relevantes());
            
            ps.setInt(12,this.id_historia);
        
            //Hacemos esto para que se cree la siguiente ventana y que salga el mensaje de que se guardo en la base de datos 
            int rowsInserted = ps.executeUpdate(); // guarda datos
            if (rowsInserted > 0) { // sólo se abre si se guardó bien
                examen_complementario complementarioFrame = new examen_complementario(this.id_historia);
                complementarioFrame.setLocationRelativeTo(null); // centra el nuevo frame
                complementarioFrame.setVisible(true); // muestra la ventana
                this.dispose(); // cierra el frame actual si ya no lo necesitas
            }    
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
        //Use esto de combo boxses etc
       // String Mucosa = PielPelaje.getSelectedItem().toString();//opcion seleccionada del combo box;
      

    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfasHallazgosClinicos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboDigestivo;
    private javax.swing.JComboBox<String> ComboEndocrino;
    private javax.swing.JComboBox<String> ComboGlangleosLinfatico;
    private javax.swing.JComboBox<String> ComboHallazgosRelevantes;
    private javax.swing.JComboBox<String> ComboMusculoEsqueletico;
    private javax.swing.JComboBox<String> ComboNervioso;
    private javax.swing.JComboBox<String> ComboPalpacionRectal;
    private javax.swing.JComboBox<String> ComboPielPelaje;
    private javax.swing.JComboBox<String> ComboReproductivo;
    private javax.swing.JComboBox<String> ComboRespiratorio;
    private javax.swing.JComboBox<String> ComboUrinario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
