/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproyectpoo.View;
import com.mycompany.finalproyectpoo.DAO.Conexion;
import static com.mysql.cj.conf.PropertyKey.logger;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author manue
 */
public class interfasDiagnostico extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfasDiagnostico.class.getName());

    /**
     * Creates new form Diagnostico
     */
    private int id_historia;
    public interfasDiagnostico(int id_historia) {
        this.id_historia = id_historia;
        initComponents();
    }

    private interfasDiagnostico() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        txtDiagnosticoPresuntivo = new javax.swing.JTextField();
        txtDiagnosticoDefinitivo = new javax.swing.JTextField();
        txtEvolucion = new javax.swing.JTextField();
        txtPronostico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Diagnostico");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Tratamiento:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 230, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Diagnostico Definitivo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 180, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Diagnostico Presuntivo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 180, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Evolución:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Pronostico:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 190, 20));
        getContentPane().add(txtTratamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 370, 30));

        txtDiagnosticoPresuntivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiagnosticoPresuntivoActionPerformed(evt);
            }
        });
        getContentPane().add(txtDiagnosticoPresuntivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 370, 30));
        getContentPane().add(txtDiagnosticoDefinitivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 370, 30));
        getContentPane().add(txtEvolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 370, 30));
        getContentPane().add(txtPronostico, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 370, 30));

        jButton1.setText("Guardar");
        jButton1.setMaximumSize(new java.awt.Dimension(72, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(72, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 330, 110, 40));

        jButton2.setText("Menu Prinsipal");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finalproyectpoo/Imagenes/Marca_Final.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 830, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String DiagnosticoPresuntivo = txtDiagnosticoPresuntivo.getText();
        String DiagnosticoDefinitivo = txtDiagnosticoDefinitivo.getText();
        String Evolucion = txtEvolucion.getText();
        String Pronostico = txtPronostico.getText();
        String Tratamiento = txtTratamiento.getText();
       
        
        try (Connection con = Conexion.conectar()) {
            String sql = "INSERT INTO diagnostico (diagnostico_presuntivo, diagnostico_definitivo, evolucion,"
                    + " pronostico, tratamiento, id_historia) VALUES (?, ?, ?, ?, ?, ?)";

    java.sql.PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1, DiagnosticoPresuntivo);
    ps.setString(2, DiagnosticoDefinitivo);
    ps.setString(3, Evolucion);
    ps.setString(4, Pronostico);
    ps.setString(5, Tratamiento);
    ps.setInt(6, id_historia);

         ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Historia Clinica guardada correctamente ");}
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDiagnosticoPresuntivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiagnosticoPresuntivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiagnosticoPresuntivoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfasDiagnostico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtDiagnosticoDefinitivo;
    private javax.swing.JTextField txtDiagnosticoPresuntivo;
    private javax.swing.JTextField txtEvolucion;
    private javax.swing.JTextField txtPronostico;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
