/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproyectpoo.View;
import com.mycompany.finalproyectpoo.DAO.Conexion;
import com.mycompany.finalproyectpoo.Models.Anamnesis;
import static com.mysql.cj.conf.PropertyKey.logger;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class interfasAnamnesis extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfasAnamnesis.class.getName());
    
    
    
    /**
     * Creates new form interfasAnamnesis
     */
    private int id_historia;
    public interfasAnamnesis(int id_historia) {
        this.id_historia = id_historia;
        initComponents();
    }
 
    private interfasAnamnesis(String dieta, String preexistencia, String cirugiasPrevias, String esquemaVacunal, String ultimaDesparasitacion, String tratamientosRecientes, String viajesRealizados, String convivenciaAnimales, String motivoConsulta) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private interfasAnamnesis() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtCirugiasPrevias = new javax.swing.JTextField();
        txtPreexistencia = new javax.swing.JTextField();
        txtEsquemaVacunal = new javax.swing.JTextField();
        txtTratamientoReciente = new javax.swing.JTextField();
        txtViajesRealizados = new javax.swing.JTextField();
        txtConvivenciaAnimales = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDieta = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMotivoConsulta = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Anamnesis");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(233, 0, 217, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Preexistencia:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Cirugías Previas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Esquema Vacunal:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 150, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Tratamientos Recientes:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 190, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Última Desparasitación:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 190, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Viajes Realizados:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 150, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Convivencia Animales:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, 20));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Motivo Consulta:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 140, 20));
        getContentPane().add(txtCirugiasPrevias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 80, 20));
        getContentPane().add(txtPreexistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 80, 20));
        getContentPane().add(txtEsquemaVacunal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 80, 20));
        getContentPane().add(txtTratamientoReciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 80, 20));
        getContentPane().add(txtViajesRealizados, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 80, 20));
        getContentPane().add(txtConvivenciaAnimales, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 80, 20));

        txtDieta.setColumns(20);
        txtDieta.setRows(5);
        jScrollPane1.setViewportView(txtDieta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 230, 90));

        jButton1.setText("Guardar y Continuar");
        jButton1.setMaximumSize(new java.awt.Dimension(72, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(72, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 180, 34));

        txtMotivoConsulta.setColumns(20);
        txtMotivoConsulta.setRows(5);
        jScrollPane2.setViewportView(txtMotivoConsulta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 230, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Dieta:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 50, 20));
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 100, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finalproyectpoo/Imagenes/Marca_Final.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-200, 0, 820, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String dieta = txtDieta.getText();
        String preexistencia = txtPreexistencia.getText();
        String cirugiasPrevias = txtCirugiasPrevias.getText();
        String esquemaVacunal = txtEsquemaVacunal.getText();
        
        java.util.Date UltimaDesparasitacion = fecha.getDate();
        java.sql.Date fechaSql = new java.sql.Date(UltimaDesparasitacion.getTime());
        String tratamientosRecientes = txtTratamientoReciente.getText();
        String viajesRealizados = txtViajesRealizados.getText();
        String convivenciaAnimales = txtConvivenciaAnimales.getText();
        String motivoConsulta = txtMotivoConsulta.getText();
        

        Anamnesis anam = new Anamnesis( dieta, preexistencia, cirugiasPrevias,
            esquemaVacunal, fechaSql, tratamientosRecientes,
            viajesRealizados, convivenciaAnimales, motivoConsulta,this.id_historia);

        try (Connection con = Conexion.conectar()) {
            String sql = "INSERT INTO anamnesis (dieta, preexistencia,"
                    + " cirugias_previas, esquema_vacunal, ultima_desparasitacion,"
                    + " tratamientos_recientes, viajes_realizados, convivencia_animales,"
                    + " motivo_consulta, id_historia) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            // En este caso se hace el statement para poder imprimir por pantalla el id de la mascota
            PreparedStatement ps = con.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);

            ps.setString(1,anam.getDieta());
            ps.setString(2,anam.getPreexistencia());
            ps.setString(3, anam.getCirugias_previas());
            ps.setString(4,anam.getEsquema_vacunal());
            ps.setDate(5,(java.sql.Date)anam.getUltima_desparasitacion());
            ps.setString(6,anam.getTratamientos_recientes());
            ps.setString(7,anam.getViajes_realizados());
            ps.setString(8, anam.getConvivencia_animales());
            ps.setString(9,anam.getMotivo_consulta());
            ps.setInt(10,this.id_historia);
        
            //Hacemos esto para que se cree la siguiente ventana y que salga el mensaje de que se guardo en la base de datos 
            int rowsInserted = ps.executeUpdate(); // guarda datos
            if (rowsInserted > 0) { // sólo se abre si se guardó bien
                examen_fisico examen_fisicoFrame = new examen_fisico(this.id_historia);
                examen_fisicoFrame.setLocationRelativeTo(null); // centra el nuevo frame
                examen_fisicoFrame.setVisible(true); // muestra la ventana
                this.dispose(); // cierra el frame actual si ya no lo necesitas
            }
            
        } 
        catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfasAnamnesis().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCirugiasPrevias;
    private javax.swing.JTextField txtConvivenciaAnimales;
    private javax.swing.JTextArea txtDieta;
    private javax.swing.JTextField txtEsquemaVacunal;
    private javax.swing.JTextArea txtMotivoConsulta;
    private javax.swing.JTextField txtPreexistencia;
    private javax.swing.JTextField txtTratamientoReciente;
    private javax.swing.JTextField txtViajesRealizados;
    // End of variables declaration//GEN-END:variables
}
