/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproyectpoo.View;

import com.mycompany.finalproyectpoo.DAO.Conexion;
import com.mycompany.finalproyectpoo.Models.Historia_Clinica;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author juana
 */
public class interfasHistoriaClinica extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfasHistoriaClinica.class.getName());
    
    /**
     * Creates new form interfasHistoriaClinica
     */
    public interfasHistoriaClinica() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtid_veterinario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtfecha = new com.toedter.calendar.JDateChooser();
        txtid_mascota = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Crear Historia Clinica");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 18, 329, 38));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Fecha de la H.C:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 133, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Id Veterinario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 112, -1));

        txtid_veterinario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_veterinarioActionPerformed(evt);
            }
        });
        getContentPane().add(txtid_veterinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 134, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Id Mascota:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 112, -1));
        getContentPane().add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 134, -1));

        txtid_mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid_mascotaActionPerformed(evt);
            }
        });
        getContentPane().add(txtid_mascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 134, -1));

        jButton2.setText("Guardar y Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 150, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finalproyectpoo/Imagenes/Marca_Final.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, 830, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtid_veterinarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_veterinarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_veterinarioActionPerformed

    private void txtid_mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid_mascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid_mascotaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int id_veterinario = Integer.parseInt(txtid_veterinario.getText());
        java.util.Date fechaSeleccionada = txtfecha.getDate();
        java.sql.Date fechaSql = new java.sql.Date(fechaSeleccionada.getTime());
        int id_mascota = Integer.parseInt(txtid_mascota.getText());
        //Creamos objeto historia clinica
        Historia_Clinica hc = new Historia_Clinica(id_veterinario, id_mascota, fechaSql);
        
       
        try (Connection con = Conexion.conectar()) {
        String sql = "INSERT INTO historia_clinica ( id_veterinario, id_mascota, fecha_creacion"+ ") VALUES (?, ?, ?)";
        
        // En este caso se hace el statement para poder imprimir por pantalla el id de la mascota
        PreparedStatement ps = con.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);
        
        ps.setInt(1,hc.getId_veterinario());
        ps.setInt(2,hc.getId_mascota());
        ps.setDate(3, (java.sql.Date) hc.getFecha_creacion());
        
        
        ps.executeUpdate();
        
        ResultSet rs = ps.getGeneratedKeys();
        if (rs.next()) {
            int id_hc = rs.getInt(1);
            interfasAnamnesis anamnesisFrame = new interfasAnamnesis(id_hc);
            anamnesisFrame.setLocationRelativeTo(null);
            anamnesisFrame.setVisible(true);
            JOptionPane.showMessageDialog(this, "Id_Historia clinica es : " + id_hc);}
            this.dispose(); // cierra el frame actual si ya no lo necesitas
            
        }
        catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar: " + e.getMessage());
        }

        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfasHistoriaClinica().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private com.toedter.calendar.JDateChooser txtfecha;
    private javax.swing.JTextField txtid_mascota;
    private javax.swing.JTextField txtid_veterinario;
    // End of variables declaration//GEN-END:variables
}
