/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.finalproyectpoo.View;

/**
 *
 * @author manue
 */
public class interfasHallazgosClinicos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(interfasHallazgosClinicos.class.getName());

    /**
     * Creates new form interfasHallazgosClinicos
     */
    public interfasHallazgosClinicos() {
        initComponents();
    }

    interfasHallazgosClinicos(int id_historia) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PielPelaje = new javax.swing.JComboBox<>();
        GlangleosLinfatico = new javax.swing.JComboBox<>();
        Digestivo = new javax.swing.JComboBox<>();
        Respiratorio = new javax.swing.JComboBox<>();
        Endocrino = new javax.swing.JComboBox<>();
        Nervioso = new javax.swing.JComboBox<>();
        Urinario = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Reproductivo = new javax.swing.JComboBox<>();
        MusculoEsqueletico = new javax.swing.JComboBox<>();
        PalpacionRectal = new javax.swing.JComboBox<>();
        HallazgosRelevantes = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Glangleos Linfatico:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 170, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Piel y Pelaje:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Digestivo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 20));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Respiratorio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 190, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("Endocrino:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Nervioso:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 150, 20));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setText("Urinario:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setText("Hallazgos Clinicos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 300, 40));

        PielPelaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Alopecia (pérdida de pelo)", "Presencia de pulgas o garrapatas" }));
        PielPelaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PielPelajeActionPerformed(evt);
            }
        });
        getContentPane().add(PielPelaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 110, -1));

        GlangleosLinfatico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normales", "Aumentados de tamaño", "Dolorosos a la palpación" }));
        getContentPane().add(GlangleosLinfatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 110, -1));

        Digestivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Vómitos", "Diarrea" }));
        Digestivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DigestivoActionPerformed(evt);
            }
        });
        getContentPane().add(Digestivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 110, -1));

        Respiratorio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Tos", "Dificultad respiratoria (disnea)" }));
        Respiratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RespiratorioActionPerformed(evt);
            }
        });
        getContentPane().add(Respiratorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 110, -1));

        Endocrino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Polidipsia / Poliuria (mucha sed o micción)", "Pérdida de peso sin causa aparente" }));
        getContentPane().add(Endocrino, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 110, -1));

        Nervioso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Convulsiones", "Descoordinación (ataxia)" }));
        getContentPane().add(Nervioso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, -1));

        Urinario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Dificultad para orinar (disuria)", "Orina con sangre (hematuria)" }));
        getContentPane().add(Urinario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 110, -1));

        jButton1.setText("Guardar");
        jButton1.setMaximumSize(new java.awt.Dimension(72, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(72, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 104, 34));

        jButton2.setText("Continuar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 104, 34));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Reproductivo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Músculo Esqueletico:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("Palpación Rectal:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("Hallazgo Relevantes:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        Reproductivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Secreción vaginal o prepucial", "Inflamación genital o testicular" }));
        getContentPane().add(Reproductivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, 100, -1));

        MusculoEsqueletico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Cojera", "Dolor articular" }));
        getContentPane().add(MusculoEsqueletico, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 100, -1));

        PalpacionRectal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Dolor a la palpación", "Masas o engrosamientos detectables" }));
        getContentPane().add(PalpacionRectal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 100, -1));

        HallazgosRelevantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin hallazgos relevantes", "Lesiones múltiples", "Signos de dolor o malestar general" }));
        getContentPane().add(HallazgosRelevantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 100, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/finalproyectpoo/Imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PielPelajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PielPelajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PielPelajeActionPerformed

    private void DigestivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DigestivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DigestivoActionPerformed

    private void RespiratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RespiratorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RespiratorioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new interfasHallazgosClinicos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Digestivo;
    private javax.swing.JComboBox<String> Endocrino;
    private javax.swing.JComboBox<String> GlangleosLinfatico;
    private javax.swing.JComboBox<String> HallazgosRelevantes;
    private javax.swing.JComboBox<String> MusculoEsqueletico;
    private javax.swing.JComboBox<String> Nervioso;
    private javax.swing.JComboBox<String> PalpacionRectal;
    private javax.swing.JComboBox<String> PielPelaje;
    private javax.swing.JComboBox<String> Reproductivo;
    private javax.swing.JComboBox<String> Respiratorio;
    private javax.swing.JComboBox<String> Urinario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
